CREATE TABLE EntregasProjetos (
    ITEM_ID INT PRIMARY KEY,
    ITEM_NAME VARCHAR(255),
    TARGET_DATE DATE,
    COLUMN_NAME VARCHAR(100),
    LANE VARCHAR(100),
    BLOCK_TIME INT,
    IS_BLOCKED BIT,
    PRIORITY INT,
    SECTION VARCHAR(100),
    DATA_INICIO_ENTREGA DATETIME,
    DATA_FIM_ENTREGA DATETIME,
    SECAO VARCHAR(100)
);