
-- Projetos entregues por ano
SELECT ANO_ENTREGA, COUNT(*) AS QTDE_ENTREGUES
FROM EntregasProjetos
WHERE DATA_FIM_ENTREGA IS NOT NULL
GROUP BY ANO_ENTREGA
ORDER BY ANO_ENTREGA;

-- Projetos não entregues
SELECT ITEM_NAME
FROM EntregasProjetos
WHERE DATA_FIM_ENTREGA IS NULL;

-- Entregas por trimestre
SELECT ANO_ENTREGA, TRIMESTRE_ENTREGA, COUNT(*) AS TOTAL
FROM EntregasProjetos
GROUP BY ANO_ENTREGA, TRIMESTRE_ENTREGA
ORDER BY ANO_ENTREGA, TRIMESTRE_ENTREGA;
